### ISSUE TITLE
Showing active current plan on billing page

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#21]
When selecting a plan, it shows up as active on the plan page but only when the same (monthly/annually mode is selected). Otherwise, the highlighting disappears.

### Example:

![](https://i.imgur.com/8hHoRqR.png)

Background color for active disappears when in annual plan mode.

![](https://i.imgur.com/mj7SnFQ.png)

**Comment by farhan687** [comment]
We are already showing that sub-header below monthly/annually button.

We should not event show 'current plan' on different mode. Because it's different plan 'bootstrap-monthly' and 'bootstrap-annaul' is different.

suppose if you want to convert from bootstrap-monthly to bootstrap-annually, how will you do that?

**Comment by siddharthlatest** [comment]
@farhan687 Good point, lets stop showing the current plan label.
