### ISSUE TITLE
v2 launch

### ISSUE THREAD

**Issue by metagrover** [appbaseio/dashboard#59]
## In-app views

- [x] Trial state in reducers + component hooks
- [x] connect upgrade buttons in in-app views
- [x] navbar - back button for dashboard (@jyash97)
- [x] sidebar - add appbase logo (@jyash97)
- [x] Rename search sandbox to search preview (@jyash97)

@bietkul 
- [x] App overview Screen (@siddharthlatest review and test)
- [x] Sidebar billing banner - hide it
- [x] Selected tab status for billing page
- [x] billing page - current plan status + active plan buttons
- [x] new charts for analytics [wip]

## global

- [x] Apps sharing endpoint
- [x] create new app
- [x] google-analytics + hotjar + hubspot integration (@jyash97)
- [x] Sort dropdown for apps dashboard - use metrics from redux store - reverse order (@jyash97)
- [x] interactive tutorial porting
- [x] Add support for `view` param in app-dashboard routing
- [x] share, clone, copy creds, delete button on app cards
- [x] mobile responsive
- [x] content changes (in-app views + global) (@siddharthlatest)
- [x] clusters porting
- [x] clusters fixes

## make batteries dejavu + r-apps friendly
- [ ] Mappings
- [ ] Search preview

**Comment by siddharthlatest** [comment]
### Adding issues that I am seeing after testing the UI:

- [ ] Add favicon icon for dashboard.

- [ ] The dashboard's navbar should be sticky and shouldn't move when scrolling down ![](https://i.imgur.com/7h4Y31X.png)

- [ ] The scroll happens here even though there's no further content to be scrolled ![](https://i.imgur.com/hQezfrl.png)

- [ ] Billing Ux issue - this component's style is out of sync. ![](https://i.imgur.com/xm2ekJP.png). The trial period stat should only be printed if the user is on a trial plan. This should be omitted otherwise.

- [ ] Analytics: Tabs are missing for Geo and search stats charts.

- [ ] Update the primary button styles. The old styles are used in Analytics view, Mappings view and Security Credentials view.

- [ ] @bietkul This tab should no longer be present now that we have a nested menu on the sidebar ![](https://i.imgur.com/DhsBQtV.png).

- [ ] @bietkul I don't see any chart on the search latency stat.

- [ ] @bietkul If the country visualization has no data, it should still display a map of the countries.

**Comment by siddharthlatest** [comment]
- [ ] When I do a `Sort by Recent`, the app names get changed to app ids. This is an important bug @jyash97 
![](https://i.imgur.com/xocbusS.png)
It seems the sort happens correctly.

**Comment by siddharthlatest** [comment]
UI difference:

- [ ] @metagrover You are using this style for all the Develop Pages

![](https://i.imgur.com/SjsKtwN.png)

and @bietkul is using this style for all the Analytics Pages.

![](https://i.imgur.com/oQ91WDG.png)

Can we standardize on one?

- [ ] @bietkul Can you also add a section on the pages where there is none?

![](https://i.imgur.com/jcazL9l.png)

**Comment by siddharthlatest** [comment]
- [ ] @jyash97 Submit form on Hubspot throws a 400 error when I tested it. Can you try getting someone else to test it?

**Comment by jyash97** [comment]
@siddharthlatest It is working properly, tested with different email. Getting the response 💯
